name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: gilliangoud
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: "true"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --tag ${{ env.DOCKER_USERNAME }}/ammconverter:${{ github.sha }} .
          docker tag ${{ env.DOCKER_USERNAME }}/ammconverter:${{ github.sha }} ${{ env.DOCKER_USERNAME }}/ammconverter:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/ammconverter:${{ github.sha }}
          docker push ${{ env.DOCKER_USERNAME }}/ammconverter:latest
